#ifndef GUARD_CONSTANTS_BERRY_H
#define GUARD_CONSTANTS_BERRY_H

#define BERRY_NONE 0

#define BERRY_FIRMNESS_UNKNOWN     0
#define BERRY_FIRMNESS_VERY_SOFT   1
#define BERRY_FIRMNESS_SOFT        2
#define BERRY_FIRMNESS_HARD        3
#define BERRY_FIRMNESS_VERY_HARD   4
#define BERRY_FIRMNESS_SUPER_HARD  5

#define BERRY_COLOR_RED    0
#define BERRY_COLOR_BLUE   1
#define BERRY_COLOR_PURPLE 2
#define BERRY_COLOR_GREEN  3
#define BERRY_COLOR_YELLOW 4
#define BERRY_COLOR_PINK   5

#define FLAVOR_SPICY   0
#define FLAVOR_DRY     1
#define FLAVOR_SWEET   2
#define FLAVOR_BITTER  3
#define FLAVOR_SOUR    4
#define FLAVOR_COUNT   5

#define BERRY_STAGE_NO_BERRY    0  // there is no tree planted and the soil is completely flat.
#define BERRY_STAGE_PLANTED     1
#define BERRY_STAGE_SPROUTED    2
#define BERRY_STAGE_TALLER      3
#define BERRY_STAGE_FLOWERING   4
#define BERRY_STAGE_BERRIES     5
#define BERRY_STAGE_TRUNK       6 // These follow BERRY_STAGE_BERRIES to preserve save compatibility
#define BERRY_STAGE_BUDDING     7
#define BERRY_STAGE_SPARKLING   255

// Berries can be watered in the following stages:
// - BERRY_STAGE_PLANTED
// - BERRY_STAGE_SPROUTED
// - BERRY_STAGE_TALLER
// - BERRY_STAGE_FLOWERING
#define NUM_WATER_STAGES 4

// IDs for berry tree objects, indexes into berryTrees in SaveBlock1
// Named for whatever berry is initially planted there on a new game
// Those with no initial berry are named "soil"

// Jinnora: added breaks between areas, reordered, and modified

//Route 102
#define BERRY_TREE_ROUTE_102_BABIRI   1
#define BERRY_TREE_ROUTE_102_COBA     2


//Route 103
#define BERRY_TREE_ROUTE_103_KEE      3
#define BERRY_TREE_ROUTE_103_LEPPA    4
#define BERRY_TREE_ROUTE_103_MARANGA  5


//Route 104
#define BERRY_TREE_ROUTE_104_FIGY     6
#define BERRY_TREE_ROUTE_104_MAGO     7
#define BERRY_TREE_ROUTE_104_AGUAV    8
#define BERRY_TREE_ROUTE_104_IAPAPA   9

#define BERRY_TREE_ROUTE_104_CHERI    10
#define BERRY_TREE_ROUTE_104_WIKI     11
#define BERRY_TREE_ROUTE_104_LEPPA    12

#define BERRY_TREE_ROUTE_104_ORAN     13
#define BERRY_TREE_ROUTE_104_TANGA    14
#define BERRY_TREE_ROUTE_104_PECHA    15


//Route 110
#define BERRY_TREE_ROUTE_110_CHERI   16
#define BERRY_TREE_ROUTE_110_WACAN   17
#define BERRY_TREE_ROUTE_110_BABIRI  18


//Route 111
#define BERRY_TREE_ROUTE_111_RAZZ_1   19
#define BERRY_TREE_ROUTE_111_RAZZ_2   20

#define BERRY_TREE_ROUTE_111_SHUCA    21
#define BERRY_TREE_ROUTE_111_OCCA     22


//Route 112
#define BERRY_TREE_ROUTE_112_RAWST    23
#define BERRY_TREE_ROUTE_112_PECHA    24
#define BERRY_TREE_ROUTE_112_ASPEAR   25
#define BERRY_TREE_ROUTE_112_PAYAPA   26


//Route 114
#define BERRY_TREE_ROUTE_114_PERSIM_1 27
#define BERRY_TREE_ROUTE_114_PERSIM_2 28
#define BERRY_TREE_ROUTE_114_PERSIM_3 29


//Route 115
#define BERRY_TREE_ROUTE_115_TAMATO_1 30
#define BERRY_TREE_ROUTE_115_TAMATO_2 31

#define BERRY_TREE_ROUTE_115_KELPSY_1 32
#define BERRY_TREE_ROUTE_115_KELPSY_2 33
#define BERRY_TREE_ROUTE_115_KELPSY_3 34


//Route 116
#define BERRY_TREE_ROUTE_116_CHILAN  35
#define BERRY_TREE_ROUTE_116_CHESTO  36
#define BERRY_TREE_ROUTE_116_PERSIM  37
#define BERRY_TREE_ROUTE_116_CHARTI  38


//Route 117
#define BERRY_TREE_ROUTE_117_WIKI     39
#define BERRY_TREE_ROUTE_117_AGUAV    40
#define BERRY_TREE_ROUTE_117_IAPAPA   41


//Route 118
#define BERRY_TREE_ROUTE_118_SITRUS_1 42
#define BERRY_TREE_ROUTE_118_MAGO     43
#define BERRY_TREE_ROUTE_118_SITRUS_2 44


//Route 119
#define BERRY_TREE_ROUTE_119_POMEG_1  45
#define BERRY_TREE_ROUTE_119_POMEG_2  46
#define BERRY_TREE_ROUTE_119_POMEG_3  47

#define BERRY_TREE_ROUTE_119_HONDEW_1 48
#define BERRY_TREE_ROUTE_119_HONDEW_2 49

#define BERRY_TREE_ROUTE_119_SITRUS   50
#define BERRY_TREE_ROUTE_119_LEPPA    51


//Route 120
#define BERRY_TREE_ROUTE_120_RABUTA   52
#define BERRY_TREE_ROUTE_120_LEPPA    53
#define BERRY_TREE_ROUTE_120_NOMEL    54

#define BERRY_TREE_ROUTE_120_BLUK     55
#define BERRY_TREE_ROUTE_120_CORNN    56
#define BERRY_TREE_ROUTE_120_MAGOST   57

#define BERRY_TREE_ROUTE_120_RAZZ     58
#define BERRY_TREE_ROUTE_120_NANAB    59
#define BERRY_TREE_ROUTE_120_PINAP    60
#define BERRY_TREE_ROUTE_120_WEPEAR   61


//Route 121
#define BERRY_TREE_ROUTE_121_PERSIM   62
#define BERRY_TREE_ROUTE_121_ASPEAR   63
#define BERRY_TREE_ROUTE_121_RAWST    64
#define BERRY_TREE_ROUTE_121_CHESTO   65

#define BERRY_TREE_ROUTE_121_KASIB    66
#define BERRY_TREE_ROUTE_121_COLBUR   67
#define BERRY_TREE_ROUTE_121_RINDO    68
#define BERRY_TREE_ROUTE_121_ORAN     69


//Route 123
#define BERRY_TREE_ROUTE_123_QUALOT_1 70
#define BERRY_TREE_ROUTE_123_QUALOT_2 71
#define BERRY_TREE_ROUTE_123_QUALOT_3 72
#define BERRY_TREE_ROUTE_123_QUALOT_4 73
#define BERRY_TREE_ROUTE_123_POMEG_1  74
#define BERRY_TREE_ROUTE_123_POMEG_2  75
#define BERRY_TREE_ROUTE_123_POMEG_3  76
#define BERRY_TREE_ROUTE_123_POMEG_4  77
#define BERRY_TREE_ROUTE_123_GREPA_1  78
#define BERRY_TREE_ROUTE_123_GREPA_2  79
#define BERRY_TREE_ROUTE_123_GREPA_3  80
#define BERRY_TREE_ROUTE_123_GREPA_4  81

#define BERRY_TREE_ROUTE_123_LEPPA_1  82
#define BERRY_TREE_ROUTE_123_WIKI     83
#define BERRY_TREE_ROUTE_123_LEPPA_2  84

#define BERRY_TREE_ROUTE_123_PECHA    85
#define BERRY_TREE_ROUTE_123_SITRUS   86
#define BERRY_TREE_ROUTE_123_RAWST    87


//Mirage Island
#define BERRY_TREE_ROUTE_130_LIECHI   88


//Jinnora: begin my added berry trees:

//Oldale Town
#define BERRY_TREE_OLDALE_TOWN_OCCA         89
#define BERRY_TREE_OLDALE_TOWN_PASSHO       90
#define BERRY_TREE_OLDALE_TOWN_RINDO        91
#define BERRY_TREE_OLDALE_TOWN_WACAN        92


//Oldale Glade
#define BERRY_TREE_OLDALE_GLADE_APICOT      93
#define BERRY_TREE_OLDALE_GLADE_GANLON      94
#define BERRY_TREE_OLDALE_GLADE_MICLE       95
#define BERRY_TREE_OLDALE_GLADE_ENIGMA      96


//Route 125
#define BERRY_TREE_ROUTE_125_CUSTAP         97
#define BERRY_TREE_ROUTE_125_ROWAP          98
#define BERRY_TREE_ROUTE_125_JABOCA         99


//Route 124
#define BERRY_TREE_ROUTE_124_SITRUS         100
#define BERRY_TREE_ROUTE_124_LUM            101


//Ever Grande City
#define BERRY_TREE_EVER_GRANDE_CITY_CHERI   102
#define BERRY_TREE_EVER_GRANDE_CITY_CHESTO  103
#define BERRY_TREE_EVER_GRANDE_CITY_PECHA   104
#define BERRY_TREE_EVER_GRANDE_CITY_RAWST   105
#define BERRY_TREE_EVER_GRANDE_CITY_ASPEAR  106
#define BERRY_TREE_EVER_GRANDE_CITY_PERSIM  107


//Verdant Forest
#define BERRY_TREE_VERDANT_FOREST_ROSELI    108
#define BERRY_TREE_VERDANT_FOREST_TANGA     109
#define BERRY_TREE_VERDANT_FOREST_KEBIA     110


//Millennium Field
#define BERRY_TREE_MILLENNIUM_FIELD_LEPPA   111
#define BERRY_TREE_MILLENNIUM_FIELD_CHESTO  112
#define BERRY_TREE_MILLENNIUM_FIELD_STARF   113
#define BERRY_TREE_MILLENNIUM_FIELD_LANSAT  114


//Meteor Village
#define BERRY_TREE_METEOR_VILLAGE_HABAN     115
#define BERRY_TREE_METEOR_VILLAGE_YACHE     116
#define BERRY_TREE_METEOR_VILLAGE_LIECHI    117
#define BERRY_TREE_METEOR_VILLAGE_PETAYA    118


//Dewford Resort
#define BERRY_TREE_DEWFORD_RESORT_COLBUR    119
#define BERRY_TREE_DEWFORD_RESORT_CHOPLE    120


//Lavaridge Town
#define BERRY_TREE_LAVARIDGE_TOWN_SHUCA     121
#define BERRY_TREE_LAVARIDGE_TOWN_CHARTI    122
#define BERRY_TREE_LAVARIDGE_TOWN_FIGY      123


//Sootopolis Gardens
#define BERRY_TREE_SOOTOPOLIS_GARDENS_PASSHO 124
#define BERRY_TREE_SOOTOPOLIS_GARDENS_YACHE  125


//Mossdeep City
#define BERRY_TREE_MOSSDEEP_CITY_PAYAPA     126
#define BERRY_TREE_MOSSDEEP_CITY_BABIRI     127


// All slots used!

#define BERRY_TREES_COUNT 128

#endif // GUARD_CONSTANTS_BERRY_H
