#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(WORK_UP) \
    F(SWORDS_DANCE) \
    F(PROTECT) \
    F(ENDURE) \
    F(FALSE_SWIPE) \
    F(SUBSTITUTE) \
    F(SLEEP_TALK) \
    F(SAFEGUARD) \
    F(ROAR) \
    F(FACADE) \
    F(BODY_SLAM) \
    F(HYPER_BEAM) \
    F(GIGA_IMPACT) \
    F(NATURAL_GIFT) \
    F(BULK_UP) \
    F(BRICK_BREAK) \
    F(FOCUS_BLAST) \
    F(DRAIN_PUNCH) \
    F(DEFOG) \
    F(ROOST) \
    F(DUAL_WINGBEAT) \
    F(ACROBATICS) \
    F(TOXIC) \
    F(POISON_JAB) \
    F(GUNK_SHOT) \
    F(SLUDGE_BOMB) \
    F(SLUDGE_WAVE) \
    F(EARTHQUAKE) \
    F(EARTH_POWER) \
    F(DIG) \
    F(BULLDOZE) \
    F(SANDSTORM) \
    F(STEALTH_ROCK) \
    F(ROCK_SLIDE) \
    F(STONE_EDGE) \
    F(ROCK_TOMB) \
    F(POWER_GEM) \
    F(U_TURN) \
    F(BUG_BUZZ) \
    F(LEECH_LIFE) \
    F(SHADOW_BALL) \
    F(PHANTOM_FORCE) \
    F(IRON_DEFENSE) \
    F(IRON_HEAD) \
    F(FLASH_CANNON) \
    F(WILL_O_WISP) \
    F(SUNNY_DAY) \
    F(FLAMETHROWER) \
    F(FIRE_BLAST) \
    F(OVERHEAT) \
    F(FLAME_CHARGE) \
    F(FIRE_PUNCH) \
    F(RAIN_DANCE) \
    F(AQUA_TAIL) \
    F(FLIP_TURN) \
    F(HYDRO_PUMP) \
    F(WAVE_CRASH) \
    F(SEED_BOMB) \
    F(POWER_WHIP) \
    F(ENERGY_BALL) \
    F(GIGA_DRAIN) \
    F(GRASS_KNOT) \
    F(SOLAR_BEAM) \
    F(THUNDER_WAVE) \
    F(THUNDER_PUNCH) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(VOLT_SWITCH) \
    F(WILD_CHARGE) \
    F(CALM_MIND) \
    F(AGILITY) \
    F(AMNESIA) \
    F(REST) \
    F(REFLECT) \
    F(LIGHT_SCREEN) \
    F(TRICK_ROOM) \
    F(TRICK) \
    F(SKILL_SWAP) \
    F(TELEPORT) \
    F(PSYCHIC) \
    F(PSYSHOCK) \
    F(ZEN_HEADBUTT) \
    F(HAIL) \
    F(ICE_PUNCH) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(ICICLE_CRASH) \
    F(DRAGON_CLAW) \
    F(DRAGON_PULSE) \
    F(DRAGON_TAIL) \
    F(NASTY_PLOT) \
    F(HONE_CLAWS) \
    F(TAUNT) \
    F(DARK_PULSE) \
    F(THIEF) \
    F(FOUL_PLAY) \
    F(PLAY_ROUGH) \
    F(DAZZLING_GLEAM) \
    F(MOONBLAST) \
    F(DRAINING_KISS)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
