#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     10

#define NUM_ALTERING_CAVE_TABLES 9
#define NUM_VERDANT_FOREST_TABLES 2
#define NUM_ROUTE_103_TABLES 2
#define NUM_ROUTE_111_TABLES 2
#define NUM_ROUTE_114_TABLES 2
#define NUM_ROUTE_115_TABLES 2
#define NUM_ROUTE_117_TABLES 7

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
