gText_Intro_Welcome::
	.string "Welcome to Pokémon Emerald++!\p"
	.string "This is a fangame made with the\n"
	.string "pokeemerald-expansion decomp project.\p"
	.string "E++ is set in an open world version of \n"
	.string "the Hoenn region with expanded maps\l"
	.string "and new areas.\p"
	.string "$"

gText_Intro_Version::
	.string "Current version is E++ 0.0 pre-release.{PAUSE 48}\p"
	.string "$"

gText_Intro_MainSpeech::
	.string "Remember to set your difficulty \n"
	.string "options before leaving Ever Grande\l"
	.string "City for another destination.\p"
	.string "Please check the game's documentation\n"
	.string "to view Pokémon changes and other\l"
	.string "useful info.\p"
	.string "$"

gText_Intro_AndYouAre::
	.string "You are?$"

gText_Intro_BoyOrGirl::
	.string "Please choose your avatar.$"

gText_Intro_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Intro_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Intro_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER} who's coming to the\n"
	.string "Hoenn region as part of the new\l"
	.string "exchange student program.\p"
	.string "$"

gText_Intro_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "I hope you enjoy the world of\n"
	.string "Pokémon Emerald++!\p"
	.string "$"
