gText_Birch_Welcome::
	.string "Welcome to Pokémon Emerald Beryl!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Please check the game's documentation\n"
	.string "to view Pokémon changes and other\l"
	.string "useful info.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "You are?$"

gText_Birch_BoyOrGirl::
	.string "Please choose your avatar.$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER} who's traveling\n"
	.string "to the Hoenn region.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Hoenn is an open world waiting for you\n"
	.string "to choose your path to greatness!\p"
	.string "$"
